# Generated by Django 5.0.1 on 2024-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_stock_transaction_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
