# Generated by Django 5.0.1 on 2024-01-31 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_transaction_issued_to_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_to_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Staff deleted'), to='store.staff'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=models.SET('Product deleted'), to='store.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('User deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
