# Generated by Django 5.0.1 on 2024-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_transaction_product_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
