# Generated by Django 5.0.1 on 2024-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_staff_staff_quantity_transaction_received_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_quantity', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
