# Generated by Django 5.0.1 on 2024-02-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_issued_to_staff_transaction_issued_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product_disc',
            new_name='category',
        ),
    ]
