# Generated by Django 5.0.1 on 2024-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_request_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_items',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request_items',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
